language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.16"
    - "5.12"
    - "5.10"
before_install:
    - cpanm --quiet --notest Dist::Zilla
    - dzil authordeps | cpanm --quiet --notest
install:
    - dzil listdeps | cpanm --quiet --notest
script:
    - dzil test --all
matrix:
    allow_failures:
        - perl: "5.10"
sudo: false
