language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.16"
    - "5.12"
    - "5.10"
env:
    global:
        - builddir=./Util-Underscore-CI
        - stableperl=5.20
        - RELEASE_TESTING=1
        - AUTOMATED_TESTING=1
        - EXTENDED_TESTING=1
        - AUTHOR_TESTING=1
before_install:
    - perlbrew list
    - "perlbrew exec --with $stableperl 'cpanm --quiet --notest Dist::Zilla'"
    - "perlbrew exec --with $stableperl 'dzil authordeps | cpanm --quiet --notest'"
    - "perlbrew exec --with $stableperl 'dzil build --in $builddir'"
install:
    - '(cd $builddir && cpanm --quiet --notest --installdeps .)'
    # extra deps for author tests:
    - cpanm --quiet --notest Test::Perl::Critic Test::Pod
script:
    - '(cd $builddir && prove -lr t)'
matrix:
    allow_failures:
        - perl: "5.10"
sudo: false
